# This configuration builds the repository and runs benchmarks

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Windows_Build
    jobDisplayName: "Build only : Windows"
    agentOs: Windows
    buildArgs: -ci -all -pack
    artifacts:
    - path: artifacts/
      includeForks: true
