# Configure which branches trigger builds
trigger:
  batch: true
  branches:
    include:
    - release/2.*
    - internal/release/2.*

# Run PR validation on all branches
pr:
  branches:
    include:
    - '*'

variables:
- name: ASPNETCORE_TEST_LOG_MAXPATH
  value: "200" # Keep test log file name length low enough for artifact zipping
- name: DOTNET_HOME
  value: $(Agent.BuildDirectory)/.dotnet
- name: TeamName
  value: AspNetCore
- name: BuildNumberArg
  value: ''

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Windows_Build
    jobDisplayName: "Build and test: Windows"
    buildArgs: $(BuildNumberArg)
    codeSign: true
    beforeBuild:
    - powershell: "& ./src/Servers/IIS/tools/UpdateIISExpressCertificate.ps1"
      displayName: Setup IISExpress test certificates