# Don't run CI for this config yet. We're not ready to move official builds on to Azure Pipelines
trigger: none

# Run PR validation on all branches
pr:
  branches:
    include:
    - '*'

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: Windows_Build
    jobDisplayName: "Build and test: Windows"
    agentOs: Windows
    buildScript: ./eng/scripts/cibuild.cmd
    beforeBuild:
    - powershell: "& ./src/Servers/IIS/tools/UpdateIISExpressCertificate.ps1; & ./src/Servers/IIS/tools/update_schema.ps1"
      displayName: Setup IISExpress test certificates and schema
- template: jobs/default-build.yml
  parameters:
    jobName: MacOs_Build
    jobDisplayName: "Build and test: macOS"
    agentOs: macOs
    buildScript: ./eng/scripts/cibuild.sh
- template: jobs/default-build.yml
  parameters:
    jobName: Linux_Build
    jobDisplayName: "Build and test: Linux"
    agentOs: Linux
    buildScript: ./eng/scripts/cibuild.sh
