# Don't run CI for this config
trigger: none

# Run PR validation on all branches
pr:
  branches:
    include:
    - '*'

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: PR_FastCheck
    jobDisplayName: Fast Check
    agentOs: Windows
    buildArgs: "/t:FastCheck"
- template: jobs/default-build.yml
  parameters:
    jobName: Windows_Build
    jobDisplayName: "Build: Windows"
    agentOs: Windows
    beforeBuild:
    - powershell: "& ./src/IISIntegration/tools/UpdateIISExpressCertificate.ps1; & ./src/IISIntegration/tools/update_schema.ps1"
      displayName: Setup IISExpress test certificates and schema
- template: jobs/iisintegration-job.yml
  parameters:
    TestGroupName: IIS
    SkipIISTests: false
    SkipIISExpressTests: true
    SkipIISForwardsCompatibilityTests: true
    SkipIISBackwardsCompatibilityTests: true
- template: jobs/iisintegration-job.yml
  parameters:
    TestGroupName: IISExpress
    SkipIISTests: true
    SkipIISExpressTests: false
    SkipIISForwardsCompatibilityTests: true
    SkipIISBackwardsCompatibilityTests: true
- template: jobs/iisintegration-job.yml
  parameters:
    TestGroupName: IISForwardCompat
    SkipIISTests: true
    SkipIISExpressTests: true
    SkipIISForwardsCompatibilityTests: false
    SkipIISBackwardsCompatibilityTests: true
- template: jobs/iisintegration-job.yml
  parameters:
    TestGroupName: IISBackCompat
    SkipIISTests: true
    SkipIISExpressTests: true
    SkipIISForwardsCompatibilityTests: true
    SkipIISBackwardsCompatibilityTests: false
