
trigger:
- master
- release/*

jobs:
- template: project-ci.yml
  parameters:
    buildArgs: "/t:FastCheck"
- job: RepoBuilds
  pool:
    vmImage: vs2017-win2016
  strategy:
    maxParallel: 3
    matrix:
      DataProtection:
        _FolderName: DataProtection
      WebSockets:
        _FolderName: WebSockets
  steps:
  - script: src/$(_FolderName)/build.cmd -ci
    displayName: Run src/$(_FolderName)/build.cmd
  - task: PublishTestResults@2
    displayName: Publish test results
    condition: always()
    inputs:
      testRunner: vstest
      testResultsFiles: 'src/$(_FolderName)/artifacts/logs/**/*.trx'
- template: jobs/iisintegration-job.yml
  parameters:
    matrix:
      IISIntegration_IIS:
        TestGroupName: IIS
        SkipIISTests: false
        SkipIISExpressTests: true
        SkipIISForwardsCompatibilityTests: true
        SkipIISBackwardsCompatibilityTests: true
      IISIntegration_IISExpress:
        TestGroupName: IISExpress
        SkipIISTests: true
        SkipIISExpressTests: false
        SkipIISForwardsCompatibilityTests: true
        SkipIISBackwardsCompatibilityTests: true
      IISIntegration_IISForwardCompat:
        TestGroupName: IISForwardCompat
        SkipIISTests: true
        SkipIISExpressTests: true
        SkipIISForwardsCompatibilityTests: false
        SkipIISBackwardsCompatibilityTests: true
      IISIntegration_IISBackCompat:
        TestGroupName: IISBackCompat
        SkipIISTests: true
        SkipIISExpressTests: true
        SkipIISForwardsCompatibilityTests: true
        SkipIISBackwardsCompatibilityTests: false
    buildArgs: "/p:SkipIISBackwardsCompatibilityTests=$(SkipIISBackwardsCompatibilityTests) /p:SkipTests=$(SkipIISTests)  /p:SkipIISExpressTests=$(SkipIISExpressTests) /p:SkipIISForwardsCompatibilityTests=$(SkipIISForwardsCompatibilityTests)"
    jobName: IISIntegration_$(TestGroupName)
    jobDisplayName: IISIntegration_$(TestGroupName)
