
trigger:
- master
- release/*

jobs:
- template: project-ci.yml
  parameters:
    buildArgs: "/t:FastCheck"
- job: RepoBuilds
  pool:
    vmImage: vs2017-win2016
  strategy:
    maxParallel: 3
    matrix:
      DataProtection:
        _FolderName: DataProtection
      WebSockets:
        _FolderName: WebSockets
  steps:
  - script: src/$(_FolderName)/build.cmd -ci
    displayName: Run src/$(_FolderName)/build.cmd
  - task: PublishTestResults@2
    displayName: Publish test results
    condition: always()
    inputs:
      testRunner: vstest
      testResultsFiles: 'src/$(_FolderName)/artifacts/logs/**/*.trx'
- template: jobs/iisintegration-job.yml
  parameters:
    matrix:
      IISIntegration_IIS:
        testGroupName: IIS
        skipIISTests: false
        skipIISExpressTests: true
        skipIISForwardsCompatibilityTests: true
        skipIISBackwardsCompatibilityTests: true
      IISIntegration_IISExpress:
        testGroupName: IISExpress
        skipIISTests: true
        skipIISExpressTests: false
        skipIISForwardsCompatibilityTests: true
        skipIISBackwardsCompatibilityTests: true
      IISIntegration_IISForwardCompat:
        testGroupName: IISForwardCompat
        skipIISTests: true
        skipIISExpressTests: true
        skipIISForwardsCompatibilityTests: false
        skipIISBackwardsCompatibilityTests: true
      IISIntegration_IISBackCompat:
        testGroupName: IISBackCompat
        skipIISTests: true
        skipIISExpressTests: true
        skipIISForwardsCompatibilityTests: true
        skipIISBackwardsCompatibilityTests: false
