# We only want to run IdentityModel matrix on main
pr: none
trigger: none
schedules:
# Cron timezone is UTC.
- cron: "0 */12 * * *"
  branches:
    include:
    - main
    - release/8.0
  always: true

variables:
- name: _UseHelixOpenQueues
  value: false
- group: DotNet-HelixApi-Access
- template: /eng/common/templates/variables/pool-providers.yml

jobs:
- template: jobs/default-build.yml
  parameters:
    jobName: IdentityModel_helix_matrix_x64
    jobDisplayName: 'Tests: IdentityModel nightlies helix full matrix x64'
    agentOs: Windows
    timeoutInMinutes: 300
    steps:
    - task: NuGetAuthenticate@1
    - task: NuGetCommand@2
      displayName: Install Microsoft.IdentityModel.Logging
      inputs:
        command: 'custom'
        arguments: 'install Microsoft.IdentityModel.Logging
                    -Source https://pkgs.dev.azure.com/dnceng/internal/_packaging/identitymodel-nightlies/nuget/v3/index.json 
                    -DependencyVersion Highest -PreRelease'
    - task: NuGetCommand@2
      inputs:
      displayName: Install Microsoft.IdentityModel.Protocols.OpenIdConnect
        command: 'custom'
        arguments: 'install Microsoft.IdentityModel.Protocols.OpenIdConnect
                    -Source https://pkgs.dev.azure.com/dnceng/internal/_packaging/identitymodel-nightlies/nuget/v3/index.json 
                    -DependencyVersion Highest -PreRelease'
    - task: NuGetCommand@2
      inputs:
      displayName: Install Microsoft.IdentityModel.Protocols.WsFederation
        command: 'custom'
        arguments: 'install Microsoft.IdentityModel.Protocols.WsFederation
                    -Source https://pkgs.dev.azure.com/dnceng/internal/_packaging/identitymodel-nightlies/nuget/v3/index.json 
                    -DependencyVersion Highest -PreRelease'
    - task: NuGetCommand@2
      inputs:
      displayName: System.IdentityModel.Tokens.Jwt
        command: 'custom'
        arguments: 'install System.IdentityModel.Tokens.Jwt
                    -Source https://pkgs.dev.azure.com/dnceng/internal/_packaging/identitymodel-nightlies/nuget/v3/index.json 
                    -DependencyVersion Highest -PreRelease'
    - task: PowerShell@2
      displayName: Add IdentityModel feel to NuGet.config
      inputs:
        filePath: $(Build.SourcesDirectory)/eng/scripts/SetupIdentitySources.ps1
        arguments: -ConfigFile $(Build.SourcesDirectory)/NuGet.config
    # Build the shared framework
    - script: ./eng/build.cmd -ci -prepareMachine -nativeToolsOnMachine -nobl -all -pack -arch x64
              /p:CrossgenOutput=false /p:IsIdentityModelTestJob=true /p:ASPNETCORE_TEST_LOG_DIR=artifacts/log
      displayName: Build shared fx
    # -noBuildRepoTasks -noBuildNative -noBuild to avoid repeating work done in the previous step.
    - script: .\eng\build.cmd -ci -prepareMachine -nobl -all -noBuildRepoTasks -noBuildNative -noBuild -test
              -projects eng\helix\helix.proj /p:IsHelixJob=true
              /p:CrossgenOutput=false /p:IsIdentityModelTestJob=true /p:ASPNETCORE_TEST_LOG_DIR=artifacts/log
      displayName: Run build.cmd helix target
      env:
        HelixApiAccessToken: $(HelixApiAccessToken) # Needed for internal queues
        SYSTEM_ACCESSTOKEN: $(System.AccessToken) # We need to set this env var to publish helix results to Azure Dev Ops
    artifacts:
    - name: Helix_logs
      path: artifacts/log/
      publishOnError: true
