jobs:
- template: default-build.yml
  parameters:
    beforeBuild:
      - powershell: "& ./src/Servers/IIS/tools/UpdateIISExpressCertificate.ps1; & ./src/Servers/IIS/tools/update_schema.ps1; & ./src/Servers/IIS/tools/SetupTestEnvironment.ps1 Setup"
        displayName: Prepare repo
    afterBuild:
      - powershell: "& ./src/Servers/IIS/tools/SetupTestEnvironment.ps1 Shutdown"
        displayName: Stop AppVerifier
        condition: always()
      - task: PublishBuildArtifacts@1
        displayName: Upload logs
        condition: eq(variables['system.pullrequest.isfork'], false)
        inputs:
          artifactName: logs
          artifactType: Container
          pathtoPublish: src/IISIntegration/artifacts/logs
    buildDirectory: src/Servers/IIS
    buildArgs: "/p:SkipIISBackwardsCompatibilityTests=${{ parameters.SkipIISBackwardsCompatibilityTests }} /p:SkipIISTests=${{ parameters.SkipIISTests }} /p:SkipIISExpressTests=${{ parameters.SkipIISExpressTests }} /p:SkipIISForwardsCompatibilityTests=${{ parameters.SkipIISBackwardsCompatibilityTests }}"
    jobName: IISIntegration_${{ parameters.TestGroupName }}
    jobDisplayName: IISIntegration_${{ parameters.TestGroupName }}

