#
# Based on /.azure/pipelines/ci.yml
#

name: MacOS Build and Test Packaging

on: [push]

env:
  BuildNodejsScriptArgs: >
    --build-nodejs

  BuildScriptArgs: >
    --pack
    --all
    --no-build-java
    -p:SkipTestBuild=true
    -p:OnlyPackPlatformSpecificPackages=true
    -p:AssetManifestFileName=aspnetcore-MacOS_x64.xml

jobs:
  Build-MacOs:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Echo Build Command
        working-directory: ./eng
        run: echo ./build.sh ${{ env.BuildScriptArgs }}
      - name: Restore
        run: ./restore.sh
      - name: Build nodejs
        working-directory: ./eng
        run: source ../activate.sh && ./build.sh ${{ env.BuildNodejsScriptArgs }} || true
      - name: Build
        working-directory: ./eng
        run: source ../activate.sh && ./build.sh ${{ env.BuildScriptArgs }}
