name: AspNetCore-Runtime Code Sync
on:
  # While testing
  push
  # schedule:
    # * is a special character in YAML so you have to quote this string
    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
    # - cron:  '*/5 * * * *'

jobs:
  compare_repos:
    name: Compare the shared code in the AspNetCore and Runtime repos and notify if they're out of sync.
    runs-on: windows-latest
    steps:
    - name: Checkout aspnetcore
      uses: actions/checkout@v2.0.0
      with:
        path: aspnetcore
    - name: Checkout runtime
      uses: actions/checkout@v2.0.0
      with:
        # repository: 'dotnet/runtime'
        repository: 'Tratcher/runtime'
        path: runtime
    - name: Copy
      shell: cmd
      working-directory: .\runtime\src\libraries\Common\src\System\Net\Http\aspnetcore\
      env:
        ASPNETCORE_REPO: d:\a\aspnetcore\aspnetcore\aspnetcore\
      run: |
        dir
        CopyToAspNetCore.cmd
    - name: Diff
      shell: cmd
      working-directory: .\aspnetcore\
      run: |
        mkdir ..\artifacts
        git status > ..\artifacts\status.txt
        git diff > ..\artifacts\diff.txt
    - uses: actions/upload-artifact@v1
      with:
        name: results
        path: artifacts
    - name: Check and Notify
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Check the code is in sync
        $changed = (select-string "nothing to commit" artifacts\status.txt).count -eq 0
        if (-not $changed) { exit }
        # Check if issue #18943 is open/closed
        $Base64Token = [System.Convert]::ToBase64String([char[]]$ENV:GITHUB_TOKEN);
        $Headers = @{ Authorization = 'Basic {0}' -f $Base64Token; };
        $result = Invoke-RestMethod -Uri https://api.github.com/repos/dotnet/aspnetcore/issues/18943
        if ($result.state -eq "closed") { 
         $body = "{ `"state`": `"open`" }"
         $result = Invoke-RestMethod -Method PATCH -Headers $Headers -Uri https://api.github.com/repos/dotnet/aspnetcore/issues/18943 -Body $body
        }
        # Add a comment
        $body = "{ `"body`": `"Test message: The code is out of sync.`" }"
        $result = Invoke-RestMethod -Method POST -Headers $Headers -Uri https://api.github.com/repos/dotnet/aspnetcore/issues/18943 -Body $body
