name: AspNetCore-Runtime Code Sync
on:
  # While testing
  push
  # schedule:
    # * is a special character in YAML so you have to quote this string
    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
    # - cron:  '*/5 * * * *'

jobs:
  compare_repos:
    name: Compare the shared code in the AspNetCore and Runtime repos and notify if they're out of sync.
    runs-on: windows-latest
    steps:
    - name: Checkout aspnetcore
      uses: actions/checkout@v2.0.0
      with:
        path: aspnetcore
    - name: Checkout runtime
      uses: actions/checkout@v2.0.0
      with:
        # repository: 'dotnet/runtime'
        repository: 'Tratcher/runtime'
        path: runtime
    - name: Copy
      shell: cmd
      working-directory: .\runtime\src\libraries\Common\src\System\Net\Http\aspnetcore\
      env:
        ASPNETCORE_REPO: d:\a\aspnetcore\aspnetcore\aspnetcore\
      run: |
        dir
        CopyToAspNetCore.cmd
    - name: Diff
      shell: cmd
      working-directory: .\aspnetcore\
      run: |
        mkdir ..\artifacts
        git status > ..\artifacts\status.txt
        git diff > ..\artifacts\diff.txt
    - uses: actions/upload-artifact@v1
      with:
        name: results
        path: artifacts
    - name: Check
      shell: cmd
      # Returns 0 if found, 1 otherwise
      run: findstr /c:"nothing to commit, working tree clean" artifacts\status.txt
    - name: Notify
      if: failure()
      shell: cmd
      run: echo "The Check task failed, sending notification."
